version: 2.1

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - integrated_test:
          requires:
            - unit_test
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
commands:
  bootstrap:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

jobs:
  build:
    docker:
      - image: node:16
    working_directory: ~/repo
    steps:
      - checkout
      - bootstrap
      - run: yarn format:check
      - run: yarn build
      - run: yarn lint

  unit_test:
    docker:
      - image: node:16
    working_directory: ~/repo
    steps:
      - checkout
      - bootstrap
      - run: yarn test

  integrated_test:
    docker:
      - image: regviz/node-xcb
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    steps:
      - checkout
      - bootstrap
      - run: yarn e2e
  #     - run: yarn regression

  deploy:
    docker:
      - image: node:16
    working_directory: ~/repo
    steps:
      - checkout
      - bootstrap
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish
          command: |
            yarn deploy:ci
