version: 2
jobs:
  build:
    docker:
      - image: regviz/node-xcb

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
      - run: cd examples/react; yarn; cd ../..
      - run: cd examples/angular; yarn; cd ../..
      - run: yarn test
