version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: regviz/node-xcb

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:

      - checkout

      - run: yarn install

      - run: cd examples/angular-cli/; yarn install; cd ../..

      # see  https://github.com/storybooks/storybook/issues/2602
      # - run: yarn lint
      - run: yarn e2e
